package(default_visibility = ["//visibility:public"])
load("@rules_python//python:defs.bzl", "py_binary")

py_library(
    name = "mnist_csv_loader",
    srcs = [
        "mnist_csv_loader.py"
    ],
)
