FROM ubuntu:latest

RUN apt update \
  && apt install -y curl wget git vim build-essential

RUN wget https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64 -O /usr/local/bin/bazel \
  && chmod +x /usr/local/bin/bazel && bazel

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /srv/miniconda.sh \
  && bash /srv/miniconda.sh -b -p /srv/miniconda

RUN /srv/miniconda/bin/conda install -y numpy notebook matplotlib \
  && echo "export PATH=\$PATH:/srv/miniconda/bin" >> ~/.bashrc 

WORKDIR /nn

CMD /bin/bash
