FROM ubuntu:latest

RUN apt update \
  && apt install -y curl wget git vim build-essential gnupg

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /srv/miniconda.sh \
  && bash /srv/miniconda.sh -b -p /srv/miniconda

RUN /srv/miniconda/bin/conda install -y numpy notebook matplotlib \
  && echo "export PATH=\$PATH:/srv/miniconda/bin" >> ~/.bashrc

RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
RUN mv bazel.gpg /etc/apt/trusted.gpg.d/
RUN echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list

RUN apt update \
  && apt install -y bazel

WORKDIR /nn

CMD /bin/bash
