load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "nn_src",
    srcs = [
        "activation.py",
        "cost.py",
        "layer.py",
        "model.py",
        "utils.py",
    ],
)

py_library(
    name = "utils",
    srcs = [
        "utils.py",
    ],
)
