package(default_visibility = ["//visibility:public"])
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "nn_src",
    srcs = [
        "activation.py",
        "cost.py",
        "layer.py",
        "model.py",
        "utils.py",
        "operator.py",
    ],
)
